# Generated by Django 5.2.6 on 2025-09-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('curp', models.CharField(blank=True, max_length=40, null=True)),
                ('rfc', models.CharField(blank=True, max_length=15, null=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=25, unique=True)),
                ('validity_start', models.DateField(blank=True, null=True)),
                ('validity_end', models.DateField(blank=True, null=True)),
                ('download_date', models.DateField(blank=True, null=True)),
                ('diploma_file', models.FileField(upload_to='diplomas/')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='templates/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
