# Generated by Django 5.2.6 on 2025-09-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.program'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.request'),
        ),
        migrations.AddField(
            model_name='template',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.certificatetype'),
        ),
    ]
