# Generated by Django 4.2.24 on 2025-10-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_add_status_reason_and_events'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diploma', 'Diploma'), ('dc3', 'DC3'), ('cproem', 'CPROEM')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_tokens', to='alumnos.request')),
            ],
        ),
        migrations.AddConstraint(
            model_name='doctoken',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('request', 'tipo'), name='uniq_request_tipo_active'),
        ),
    ]
