# Generated by Django 4.2.16 on 2025-11-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_designtemplate_organization_templateasset_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellidos'),
        ),
    ]
