# Generated by Django 4.2.16 on 2025-11-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_adminuser_first_name_adminuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSim',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(db_column='programa', max_length=50, verbose_name='Código')),
                ('name', models.CharField(db_column='programa_full', max_length=255, verbose_name='Nombre completo')),
                ('certificate_type', models.IntegerField(db_column='constancia', verbose_name='Tipo de constancia')),
                ('updated_at', models.DateTimeField(blank=True, db_column='update_at', null=True)),
            ],
            options={
                'db_table': 'diplomado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiplomaBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre programa')),
                ('image', models.ImageField(upload_to='diplomas/', verbose_name='Imagen de fondo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Fondo de diploma',
                'verbose_name_plural': 'Fondos de diploma',
            },
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='background_print',
            field=models.FileField(blank=True, help_text='Fondo IMPRESO (descarga final)', null=True, upload_to='plantillas/backgrounds/'),
        ),
        migrations.AddField(
            model_name='designtemplate',
            name='background_web',
            field=models.FileField(blank=True, help_text='Fondo WEB (vista previa y tracking)', null=True, upload_to='plantillas/backgrounds/'),
        ),
    ]
