# Generated by Django 4.2.16 on 2025-11-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_rejectedarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='hours',
            field=models.PositiveIntegerField(blank=True, help_text='Intensidad del programa en horas (opcional).', null=True, verbose_name='Horas de intensidad'),
        ),
    ]
