# Generated by Django 4.2.16 on 2025-11-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_graduate_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocxTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre descriptivo')),
                ('tipo', models.CharField(choices=[('diploma', 'Diploma'), ('dc3', 'Constancia DC-3'), ('cproem', 'Constancia CPROEM')], max_length=20, verbose_name='Tipo de documento')),
                ('file', models.FileField(upload_to='docx_templates/', verbose_name='Archivo DOCX')),
                ('is_active', models.BooleanField(default=True, help_text='Si hay varias activas del mismo tipo, se usará la más reciente.', verbose_name='Usar como plantilla principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla DOCX',
                'verbose_name_plural': 'Plantillas DOCX',
            },
        ),
    ]
