# Generated by Django 4.2.16 on 2025-11-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_docxtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='docx_tpl_cproem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_docx_cproem', to='administracion.docxtemplate'),
        ),
        migrations.AddField(
            model_name='program',
            name='docx_tpl_dc3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_docx_dc3', to='administracion.docxtemplate'),
        ),
        migrations.AddField(
            model_name='program',
            name='docx_tpl_diploma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_docx_diploma', to='administracion.docxtemplate'),
        ),
    ]
