# Generated by Django 4.2.24 on 2025-09-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diplomado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('programa', models.CharField(max_length=50)),
                ('programa_full', models.CharField(max_length=200)),
                ('constancia', models.IntegerField()),
            ],
            options={
                'db_table': 'diplomado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alumnos_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('curp', models.CharField(blank=True, max_length=40, null=True)),
                ('rfc', models.CharField(blank=True, max_length=15, null=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.program')),
            ],
        ),
    ]
