# Generated by Django 4.2.24 on 2025-10-05 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Solicitud enviada'), ('review', 'En revisión'), ('accepted', 'Aprobada'), ('generating', 'Diploma/Constancia generándose'), ('emailed', 'Enviado por correo'), ('downloaded', 'Descargado por el alumno'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Solicitud enviada'), ('review', 'En revisión'), ('accepted', 'Aprobada'), ('generating', 'Diploma/Constancia generándose'), ('emailed', 'Enviado por correo'), ('downloaded', 'Descargado por el alumno'), ('rejected', 'Rechazada')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alumnos.request')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
