# Generated by Django 4.2.24 on 2025-10-05 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_request_rejection_reason_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestevent',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='request',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='requestevent',
            name='created_by',
        ),
        migrations.AddField(
            model_name='request',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='alumnos.program'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('review', 'Revisión'), ('accepted', 'Aprobada'), ('rejected', 'Rechazada'), ('generating', 'Generando'), ('emailed', 'Enviado por correo'), ('downloaded', 'Descargado por el alumno')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('review', 'Revisión'), ('accepted', 'Aprobada'), ('rejected', 'Rechazada'), ('generating', 'Generando'), ('emailed', 'Enviado por correo'), ('downloaded', 'Descargado por el alumno')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['email'], name='alumnos_req_email_87f530_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='alumnos_req_status_440c44_idx'),
        ),
        migrations.AddIndex(
            model_name='requestevent',
            index=models.Index(fields=['request', 'status'], name='alumnos_req_request_886eba_idx'),
        ),
        migrations.AlterModelTable(
            name='request',
            table='alumnos_request',
        ),
        migrations.AlterModelTable(
            name='requestevent',
            table='alumnos_request_event',
        ),
    ]
