# Generated by Django 4.2.25 on 2025-10-21 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_add_status_reason_and_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterField(
            model_name='request',
            name='sent_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
