# Generated by Django 4.2.16 on 2025-11-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_program_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('review', 'Revisión'), ('accepted', 'Aprobada'), ('rejected', 'Rechazada'), ('generating', 'Generando'), ('emailed', 'Enviado por correo'), ('downloaded', 'Descargado por el alumno'), ('finalizado', 'Finalizado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('review', 'Revisión'), ('accepted', 'Aprobada'), ('rejected', 'Rechazada'), ('generating', 'Generando'), ('emailed', 'Enviado por correo'), ('downloaded', 'Descargado por el alumno'), ('finalizado', 'Finalizado')], max_length=20),
        ),
    ]
