# Generated by Django 4.2.16 on 2025-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_request_status_alter_requestevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
